### ISSUE TITLE
Generic Netconf modules for managing Netconf enabled network devices

### ISSUE THREAD

**Issue by ganeshrn** [ansible/proposals#104]
# Proposal: <proposal name>
Generic Netconf modules to support network platforms that are Netconf enabled
*Author*: Ganesh B. Nalawade @ganeshrn

*Date*: 2018/04/11

- Status: New
- Proposal type: core design
- Targeted Release: 2.6
- Associated PR: <link to GH PR in ansible/proposals if PR was submitted>
- Estimated time to implement: 4 weeks

## Motivation
Describe the reasons for this proposal.
Provide generic Netconf modules that can communicate with the network device that supports Netconf
### Problems
What problems exist that this proposal will solve?
* As a user, I want to connect to any Netconf enabled remote device and fetch configuration from running/ startup datastore based on device capability.
* As a user, I want to connect to any Netconf enabled remote device and fetch operational state data 
* As a user, I want to connect to any Netconf enabled remote device and edit the configuration running/candidate datastore based on device capability.
* As a user, I want to connect to any Netconf enabled remote device and execute any arbitrary Netconf RPC that is supported by remote device.
* As a user, I want Netconf existing and new modules to work with `connection: local` and `connection:netconf` that uses underlying persistent connection framework.
* Depecreate the credentials and connection specific options currently added in `netconf_config` module.

## Solution proposal
* `netconf_get` module:
The module fetch configuration and state data from remote Netconf enabled host.
Options:
  ~1. `data_type`: Identity which data needs to be fetched ie. configuration or state data. Valid values are `config` and `state` and default to `config`~
  1. `filter`: This argument specifies the XML string which acts as a filter to restrict the portions of
        the data to be are retrieved from remote device. If this option is not specified entire
        configuration or state data is returned in result depending on the value of `source`
        option. The `filter` value can be either xml string or xpath, if the filter is in
        xpath format the Netconf server running on remote host should support xpath capabiltiy
        else it will result in error.
  2. `source`:  This argument specifies the datastore from which configuration data should be fetched. Valid values are running, candidate and auto. If the value is auto it fetched configuration data from I(candidate) datastore and if candidate datastore is not supported it fallback to running datastore. If the source value is not mentioned in that case both configuration and state information in returned in response from running datastore
choices: ['running', 'candidate', 'auto', 'startup'].
  ~3. `filter_type`:  This argument specifies the type of filter, valid values are subtree and xpath. If value is subtree the value of option filter should be a xml string, if the value is xpath the value of option filter should be a xml xpath. The value xpath is supported only if Netconf server running on remote host supports xpath capability.
choices: ['subtree', 'xpath']
default: `subtree`~
  4. `display`:  Encoding scheme to use when serializing output from the device. Currently supported option value is `json` only. If the option value is I(json) it requires jxmlease to be installed on control node.
choices: ['json']

* `netconf_config` module:
The module will be used to edit the configuration, copy the configuration from one datastore to another or delete a complete configuration datastore on remote Netconf enabled host.
Options:
  1. `content`: It is XML string with a hierarchy of configuration data as defined by the device's data models. aliases: `xml`. The xml string must be rooted in the `config` element. Use lookup plugins for loading content from disk file.
  2. `target`: Name of the configuration datastore to be edited. Valid values are `auto`, `candidate`, `running`,  `startup` or remote URL.  `auto`, uses candidate and fallback to running.
  3. `default_operation`:  The default operation that needs to be performed on candidate datastore. Valid values are `merge`, `replace` and `none`. The default value is `merge`. merge:  If the value is `merge` the configuration data in the `config` option is merged with the configuration at the corresponding level in the target datastore.  If the value is `replace` the configuration data in the `config` option completely replaces the configuration in the target datastore. If the value is `none` the target datastore is unaffected by the configuration in the `config` option, unless and until the incoming configuration data uses the "operation" attribute to request a different operation.
  4. `source`:  It is the name of the configuration datastore to use as the source to copy the configuration when `copy` option is set to `True`.  The values can be either `running`, `candidate`, `startup` or a remote URL.
  5. ` confirm`: This argument will configure a timeout value for the commit to be confirmed before it is automatically rolled back.  If the `confirm_commit` argument is set to False, this argument is silently ignored.  If the value of this argument is set to 0, the commit is confirmed immediately. The remote host should support :candidate and :confirmed-commit capability for this option to work properly.
  6. `confirm_commit`: This argument will execute commit operation on the remote device. It can be used to confirm a previous commit. This is a boolean value.
  7. `backup`: This argument will cause the module to create a full backup of the current datastore value in `target` from the remote device before any changes are made.  The backup file is written to the `backup` folder in the playbook root directory.  If the directory does not exist, it is created.
  8. `copy`: It instructs the module to copy the configuration from datastore value mentioned in `source` option to datastore value mentioned in `target`. It is a boolean value
  9.  `save`: It instructs the module to save the running-config to the startup-config if changed.
  10.  `delete`: It instructs the module to delete the configuration from value mentioned in `target` datastore.

* `netconf_rpc` module: 
This module will execute generic Netconf RPC that is defined by Netconf standard as well as propriety RPC based on the Netconf capabilities supported by the remote host. 
Options:
  1. `rpc`: This is the name of netconf RPC that should be executed of remote Netconf enabled device. The Netconf RPC defined by protocol can be `lock `, `unlock`, `delete-config`, `copy-config`,  `get`, `get-config`, `close-session`, `kill-session`, `get-config`, `edit-config` along with bunch of propriety RPC supported by remote host that are specific to vendors. 

  2. `content`:  This is an XML string that identifies the payload for the `rpc` and is specific to the given `rpc` value defined in netconf standard or can be specific to the vendor supported rpc's. 

```
- name: Get confgiuration and state data
   netconf_get:

- name: Get configuration data from candidate datastore state
   netconf_get:
     source: candidate

- name: Get system configuration data from running datastore state
   netconf_get:
      source: running
      filter: <configuration><system></system></configuration>

- name: Get confgiuration and state data in json format
   netconf_get:
     display: json

- name: Get system confgiuration information using xpath filter
   netconf_get:
     source: running
     display: json
     filter: configuration/system

- name: Take backup of current configuration and edit configuration on target datastore
  netconf_config:
    content:  |
        <config xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
            <system xmlns="urn:ietf:params:xml:ns:yang:ietf-system">
                <ntp>
                    <enabled>true</enabled>
                    <server>
                        <name>ntp1</name>
                        <udp><address>127.0.0.1</address></udp>
                    </server>
                </ntp>
            </system>
        </config>
    target: running
    confirm: 0
    backup: True

- name: confirm a previous commit
  netconf_config:
    confirm_commit: True

- name: Copy configuration in running datastore to the remote host
   netconf_config: 
     target: https://user:password@example.com/cfg/new.txt
     source: running
     copy: True

- name: Execute lock on target datastore
  netconf_rpc:
    rpc: lock
    content: <target><candidate/></target>

- name: Execute platform specifc RPC 
  netconf_rpc:
     rpc: get-interface-information
```

## Testing (optional)
* Add integration and unit test for `netconf_config` module. 
* Add integration and unit test for `netconf_get` module. 
* Add integration and unit test for `netconf_rpc` module. 

## Documentation (optional)
* Update module documentation for `netconf_config`.
* Add module documentation for `netconf_get` and `netconf_rpc`.
