### ISSUE TITLE
Configurable no_log at variable level in playbook and/or tasks

### ISSUE THREAD

**Issue by ahuffman** [ansible/proposals#109]
# Proposal: Configurable no_log at variable level in playbook and/or tasks

*Author*: Andrew J. Huffman <@ahuffman> IRC: N/A

*Date*: 2018/04/23

- Status: New
- Proposal type: core design
- Targeted Release: 2.6
- Associated PR: N/A
- Estimated time to implement: ???

## Motivation
To be able to define variables that should not ever be logged to standard out with or without debugging turned on in a playbook or task, or during a task failure.  This is a huge security problem, especially when using log aggregation with Ansible Tower.  Users who are able to consume log aggregation output can inadvertently be exposed to sensitive high-level account details.

### Problems
What problems exist that this proposal will solve?
- include_vars on a vault shows all my vaulted vars in standard out with -v
- no_log on a task hides all variables and parameters, whereas I may want to all of them except one or more sensitive variables (but still shows them for some reason on a failure)

### Example 1
- Something like this would work nicely at the play level.  Today I have to put no_log on the vault include task, but other tasks may inadvertently reveal these secrets.  To hide the secrets even further I have to put no_log: True on all the other tasks that may use that var.
```yaml
---
- hosts: all
  no_log_vars:
    - my_pass1
    - my_token
    - my_pass2
  tasks:
    - name: include my vault
      include_vars: "myvault.yml"
```
The output if any of these show up in debugging should say "obfuscated" or something to that affect.
### At the task level
```yaml
- name: My command
  command: 'mycommand --user myuseracct --pass {{ pass_from_vault }}'
  no_log_vars:
    - pass_from_vault
```
If running with debugging on or the task is failed, the value of pass_from_vault should appear as "obfuscated" or something to that affect.

### Example 2
- Provide a list of no_log variables via file, so as to not clutter up a playbook with long no_log_vars lists.
```yaml
---
- hosts: all
  no_log_vars_files:
    - "hide_these_vars_from_std_out.yml"
    - "some_more_vars_to_hide.yml"
  tasks:
    - name: Do some work
      ...
```
#### Contents of hide_these_vars_from_std_out.yml
```yaml
---
no_log_vars:
  - pass1
  - mysqlpass
  - gitlab_token
  - api_token2
  - tower_admin_pass_prod
  - tower_admin_pass_dev
``` 
## Testing
The testing that should be done is as follows:
  - Do the values of variables show up when using an include_vars with debugging on and a no_log_vars or no_log_vars_files set for those variables?
  - Does the value of variables show up in any task output when either failed or debugging on and a no_log_vars or a no_log_vars_file set?
  - Do the values of variables show up in task debugging or failures when no_log_variables are set on the task?

The answer should be "no" on all the above tests, and should instead be a value of "obfuscated" or similar.

## Documentation
Yes, this would be required.
