### ISSUE TITLE
Add Ability to Change Commit Labels on IOSXR_CONFIG module

### ISSUE THREAD

**Issue by mfisher30** [ansible/proposals#117]
# Proposal: Add Ability to Change Commit Labels on `IOSXR_CONFIG` module

*Author*: Michael Fisher <@mfisher30> 

*Date*: 2018/05/22

- Status: New
- Proposal type: IOSXR_CONFIG module
- Targeted Release: 2.6

## Motivation
Currently, the IOSXR_CONFIG module allows for the addition of commit comments, but does not give the ability to add a commit label. Commit labels in many enterprise environments allow quick reference to various commits to allow for quicker rollbacks and less confusion when a rollback is needed. 

### Problems
When IOSXR_CONFIG makes a commit, it does not apply a commit label, leaving no tags for quick rollback. Rollbacks on IOS-XR devices are reference using a machine generated CommitID, but the ability to add a commit label allows the user to set a reference to the commit. 

## Solution proposal

Add an additional parameter to the IOSXR_CONFIG module that allows the addition of a commit label when the module commits a change. 

On an IOS-XR device, a commit label is added using the following configuration command

```
!
conf t
! 
commit label <word>
!
```
```

    - iosxr_config
         commands:
         comment: This is the existing parameter that allows the addition of a commit comment
         label: This is the proposed parameter that would allow the addition of a commit label
```

This will solve the inability to add a label to a commit
