### ISSUE TITLE
at module should allow direct time-of-day specification

### ISSUE THREAD

**Issue by hymie0** [ansible/proposals#124]
# Proposal: at module should allow direct time-of-day specification

*Author*: Eric B Hymowitz <@hymie0>

*Date*: 2018-07-02

- Status: New
- Proposal type: core
- Targeted Release: 
- Associated PR: 
- Estimated time to implement: 

## Motivation
The `at` module allows users to specify a command to be run a specific number of minutes/hours/days/weeks in the future.  However, the underlying `at` command allows (and arguably more often uses) a specific day/date/time to be chosen instead of a time delta in the future.

### Problems
- The `at` module does not allow a user to run a job `at 2300` 
- The `at` command allows numerous ways to specify the time for a job to be scheduled, which the `at` module does not honor:
  - HH:MM
  - midnight
  - noon
- The `at` command allows numerous ways to specify the date for a job to be scheduled, which the `at` module does not honor:
  - tomorrow
  -  \+ 3 days
  - month-name day with an optional  year
  - MMDD[CC]YY, MM/DD/[CC]YY, DD.MM.[CC]YY or [CC]YY-MM-DD

## Solution proposal
These are just examples.  Although I prefer the first two examples (timespec / optional dayspec), I have no specific belief that one method is better or more useful or easier to implement than any other
```
- name: Schedule a command to execute at 2300 this evening
  at:
    command: ls -d / >/dev/null
    timespec: 2300

- name: Schedule a command to execute at 2300 tomorrow
  at:
    command: ls -d / >/dev/null
    timespec: 2300
    dayspec: tomorrow

- name: Schedule a command to execute at 2300 on the specified date
  at:
    command: ls -d / >/dev/null
    timespec: 201807012300

- name: Schedule a command to execute at 2300 on the specified date
  at:
    command: ls -d / >/dev/null
    timespec: 2018-07-01T23:00

```
