### ISSUE TITLE
Optional "message" parameter along with "no_log: true" option

### ISSUE THREAD

**Issue by nikitakazantsev12** [ansible/proposals#145]
# Proposal: Optional "message" parameter with "no_log"

*Author*: Nikita Kazantsev <@nikitakazantsev12>

*Date*: 2018-09-27

- Status: New
- Proposal type: core design

## Motivation
If I hide task output with no_log and user with_items, I see just a lot of "changed: [...] => (item=None)" output strings.

### Problems
If there would me a kind of a "message" parameter in a task, I would be able to print some info associated with each with_items iteration. For example "message: '{{ item.mygooditemname }}'", still hiding all other things, like passwords.

## Solution proposal
```yaml
- name: my good task
  mymodule:
  username: "{{ item.user }}"
    password: "{{ item.password }}"
    filename: "{{ item.file }}"
  no_log: true
  message: "{{ item.file }}"
  with_items: "{{ user_password_file }}"
```
The target output then will look like "changed: [...] => (message=onOfMyFiles)".
