### ISSUE TITLE
Allow updating ECS/Fargate desired count without defining tasks

### ISSUE THREAD

**Issue by kraduk** [ansible/proposals#157]
# Proposal: Allow updating ECS/Fargate desired count without defining tasks

*Author*: @kraduk

*Date*: 2019-02-06

- Status: New
- Proposal type: process 
- Targeted release: future release
- Associated PR: <NA>
- Estimated time to implement: TBD

## Motivation
I have a bunch of ECS/Fargate services defined. For some reason I want to be temporarily disable all/some of these tasks. This is easy from AWS point of view as I just set the service desired count to 0.

### Problem
Background: 

We have an enforcing script that goes around shutting down non live stuff out of office hours. Due to its nature, it does not have knowledge of how the services should be defined/configured. It just looks at tags, and turns things on and off based on what it sees. Therefore destroying and recreating from known config is not an option. This works fine for RDS/Ec2 instances, but is sub optimal for our fargate services.

Issue:
On first look you can disable fargate services with the ecs_service module, when used in conjunction with ecs_service_facts. However you hit a potential snag as you cant update the desired service count, without a state option set to present. This then enforces setting the task definition. This seems to be like this as the module has been created from the service creation viewpoint where you would obviously need a task definition. This doesn't make sense in this context though. Yes we can work out the task definitions with various modules but it seems like redundant code and work here. The work around I currently use is along the lines of the below, but breaking into shell isnt great

```YAML
    - name: Get Fargate details
      ecs_service_facts:
        cluster: Staging
        region: "{{aws_region}}"
      register: ecs_services

    - debug:
        msg: "ECS Services are: {{ ecs_services.services | to_nice_json }}"

    - name: Stop services
      #ecs_service:
      #  name: "{{item}}"
      #  desired_count: 0
        #state: present
      shell: |
        aws ecs update-service \
          --cluster Staging \
          --service "{{item}}" \
          --desired-count 0
      environment:
        AWS_DEFAULT_REGION: "{{aws_region}}"
      with_items: "{{ecs_services.services}}"
```
## Solution proposal
- Have a disabled state for the service that implicitly sets the desired count to 0. We would probably also need an update state that would allow us to reset the desired count to the original value, again without redefining the task definitions. This could be extended to allow other things in the future as well.
- Insert code in snippets if you would like as shown.
```yaml
    - name: Get Fargate details
      ecs_service_facts:
        cluster: Staging
        region: "{{aws_region}}"
      register: ecs_services

    - debug:
        msg: "ECS Services are: {{ ecs_services.services | to_nice_json }}"

    - name: Stop services
      ecs_service:
        name: "{{item}}"
        desired_count: 0
        state: disabled
      with_items: "{{ecs_services.services}}"

# later on (the desired count is usually stored in a tag, which we can retrieve easily)

   - name: Restart services
      ecs_service:
        name: "{{item}}"
        desired_count: "{{some_var}}"
        state: update
      with_items: "{{ecs_services.services}}"
```
