### ISSUE TITLE
Copy in files to docker volume

### ISSUE THREAD

**Issue by ToBeReplaced** [ansible/proposals#16]
NOTE: This doesn't feel like a proposal, but rather a modification of an existing proposal. How should I have formatted this?

Most of the time that I want to create a new docker volume, it's to add configuration files to the volume before I start a container that uses it. Doing this with ansible is clunky right now. Here is an example that creates a volume "example_volume" and adds "example.j2" to it.

````
- name: Create a container with a new data volume
  docker:
    name: container
    image: centos:7
    detach: no
    volumes:
      - example_volume:/data
  become: yes

- name: Copy over the template
  template: src=example.j2 dest=/tmp/example
  become: yes

- name: Copy in the template
  command: docker cp /tmp/example container:/data/
  become: yes

- name: Remove the template
  file: path=/tmp/example state=absent
  become: yes

- name: Remove the hanging container
  docker:
    name: container
    image: centos:7
    state: absent
  become: yes
````

Is this behavior useful to others? Should it happen in docker_volume? Is it more of a "docker_copy" (and docker_template, docker_fetch)? Ex:

````
# Result is example.j2 has been templated and resides at /example on my_volume
- name: Copy in a template
  docker_template:
    src=example.j2
    dest=/example
    volume=my_volume
    image=centos:7
````
