### ISSUE TITLE
active group

### ISSUE THREAD

**Issue by pijpe00** [ansible/proposals#162]
# Proposal: active group of the play

*Author*: Edwin 

*Date*: 2018-04-09

- Status: New
- Proposal type: core
- Targeted release: 2.8
- Associated PR: -
- Estimated time to implement: <X days, weeks, etc.>

## Motivation
I want to know which group the playbook is running (ansible_play_group).

### Problems
What problems exist that this proposal will solve?
- It can helps me to include directories (directory name = the group name) with variables for a specific group

## Solution proposal
- Can you create a variable for example ansible_play_group which has the group were this play is started with

```yaml
- name: some play
    hosts: France

    roles:
    - webserver
```

```yaml
- name: include webserver info certain location
    include_vars:
    dir: '../defaults/{{ ansible_play_group }}'
    name: webinfo
```

directory structure:
.
roles
roles/webserver
roles/webserver/defaults
roles/webserver/defaults/France
roles/webserver/defaults/France/info1.yml
roles/webserver/defaults/France/info2.yml
roles/webserver/defaults/Greece
roles/webserver/defaults/Greece/info1.yml
roles/webserver/defaults/Greece/info2.yml
