### ISSUE TITLE
clone_packages - module (apt-clone)

### ISSUE THREAD

**Issue by jifox** [ansible/proposals#180]
# Proposal: clone_packages - module

*Author*: Josef Fuchs @jifox

*Date*: 2020-06-28

- Status: New
- Proposal type: (module)

## Motivation
I need to hold an ubuntu server cluster in sync. Therfore it is essential to have the same software versions installed on all servers. Also updating one system leads to the problem to replicate all the updates. 

### Problems
- Install same software packages with identical versions on multiple machines

## Solution proposal
- implement clone-packages module 
  for debian apt-clone command exists.

```yaml
    - name: Read all installed packages from current server and save as local file.
      clone_packages:
         action: clone
         dest: "~/common_software_packages_for_cluster.tar.gz"
      when: is_source_of_truth

    - name: list all packages within locally saved file
      clone_packages:
         action: info
         src: "~/common_software_packages_for_cluster.tar.gz"
      register: res_package_list
      when: is_source_of_truth

    - name: Install all packages with same version from locally saved file
      clone_packages:
         action: restore
         src: "~/common_software_packages_for_cluster.tar.gz"
      register: res_clone_packages
      when: not is_source_of_truth

    - name: Display result
      debug: |
          reboot_required:  {{ res_clone_packages.reboot_required }}
          list_of_changes: {{ res_clone_packages.changed_packages }}

    - name: Show differences
      clone_packages:
         action: restore
         src: "~/common_software_packages_for_cluster.tar.gz"
      check_mode: yes
      when: not is_source_of_truth

```
## Anything else?
It would be nice to see in the result if a reboot is required after the updates
