### ISSUE TITLE
Allow notifying handlers on OTHER HOSTS

### ISSUE THREAD

**Issue by UnitedMarsupials** [ansible/proposals#189]
# Proposal: Allow notifying handlers on OTHER HOSTS

*Author*: @UnitedMarsupials

*Date*: 2021-02-27

- Status: New
- Proposal type:
- Targeted release:
- Associated PR:
- Estimated time to implement:

## Motivation
When configuring distributed applications, it is quite common, that services on some machines need to be restarted, when something changes on _other_ machines. Unfortunately, the existing handlers-mechanism does not provide for "notifying" remote handlers -- people have to implement their own hacks...

## Solution proposal
Expand `notify` syntax to allow specifying [hosts and groups](https://docs.ansible.com/ansible/latest/user_guide/intro_patterns.html) -- still defaulting to the `inventory_hostname`, of course.

Separating handler-names from the (optional) targets can be done with the simple `@`.
```yaml
    name: Change configuration file, that service Foo downloads
      ...
    notify:
       - Restart Foo@slaves
       - Page Operator@pager
```
Alternatively, if no character can be safely chosen as such a separator -- because a handler's name can contain _any_ character -- just add another clause, such as `notify_remote`:
```yaml
    name: Change configuration file, that service Foo downloads
      ...
    notify_remote:
      slaves: Restart Foo
      pager: Page Operator
```

## Documentation (optional)
Depending on the approach chosen (expanding the existing `notify`-clause vs. creating a new `notify_remote`), the documentation would need to be updated/created...

**Comment by felixfontein** [comment]
Not sure whether the work-arounds are not the better solution, since they usually allow better control on when the handlers actually run, but an idea for your proposal: how about not adding a new keyword (`notify_remote`), but instead allowing the `notify` entries to be dictionaries:
```
  - name: Change configuration file, that service Foo downloads
      ...
    notify:
       - name: Restart Foo
         host: slaves
       - name: Page Operator
         host: pager
```
(Maybe also allow groups or multiple hosts to be mentioned?)
