### ISSUE TITLE
Integration of stat/win_stat module functionality into block and include_* to reduce boilerplate

### ISSUE THREAD

**Issue by jklaiho** [ansible/proposals#217]
One thing that I find myself constantly doing is invoking the `stat` module on a file, registering that into a variable and doing a `some_var.stat.exists` check on a block's `when` clause. The block in question is performing something like installing software from source or a GitHub release, is intended to only run once, and therefore should not be executed if one of the files it creates already exists. I've also used the same pattern to conditionalize `include_tasks` and `include_role`.

This works, but doing it is annoying boilerplate that gets old fast, and of course the registered variable lives on needlessly afterwards, too.

So I got to thinking that this kind of pattern would be an improvement:

```
- block:
    - name: download frobnitz installer from github
      get_url: ...

    - name: install frobnitz
      command: ...

    - name: adjust frobnitz ownership
      file: ...
  always:
    - name: remove frobnitz installer
      file: ...
  stat: /usr/local/bin/frobnitz
  when: not stat.exists
```

The `stat` dictionary variable (TBD what it would actually be called) should contain everything that a variable registered by a separate `stat` task would. The variable would also be local to the block; for a longer-lived variable, better to just have a separate `stat` task register it.

Likewise:

```
- include_tasks: frobnitz_install.yml
  args:
    ...
  stat: /usr/local/bin/frobnitz
  when: not stat.exists
```

It seems that about 80% of my block conditionals have to do with `stat` output, and while it may just be my particular way of working with Ansible, I'd expect that this is not all that uncommon for other people either.

If this functionality was to be added, I'd expect that `win_stat: "C:\Program Files\Frobnitz\frobnitz.exe"` should also be available and work the same way (the variable name TBD in this case as well).
