### ISSUE TITLE
Parallel playbook execution

### ISSUE THREAD

**Issue by jhawkesworth** [ansible/proposals#31]
# Proposal: Enhance Ansible to allow playbooks to be run in parallel.

_Author_: Jon Hawkesworth @jhawkesworth

_Date_: 2016/10/07
- Status: New
- Proposal type: Enhancement to core (or possibly new CLI tool)
- Targeted Release: To be decided
- Associated PR: None
- Estimated time to implement: weeks
## Motivation

Describe the reasons for this proposal.
During complex deployments, in order to keep the period of change down to the smallest possible time period, it would be very helpful if Ansible would allow (included) playbooks to be run in parallel.
### Problems

What problems exist that this proposal will solve?
- Currently I am using Jenkins to wrap up playbooks so that I can simultaneously update middleware and computer components at the same time as updating web services and front end webservers.  Wrapping each playbook in a jenkins job is a tedious manual process which I would like to replace with a top-level playbook.
## Solution proposal
- One way would be to enhance playbook includes so that a list of included playbooks causes a fork and runs all the playbooks in the list simultaneously.

So may top level playbook could look like this

```
    - include: find_release_versions.yml
    - include: synchronize_components_to_datacenter.yml
    - include: pre-deployment-checks.yml
    - include: start-deployment-notifications.yml
    - include:
         - migrate-database.yml
         - update-compute-nodes.yml
         - update-dequeuers.yml
         - update-web-services.yml
         - update-file-transfer.yml
         - update-frontend-webservers.yml
    - include: end-deployment-notifications.yml
    - include: generate-change-report.yml

```

So everything from migrate-database.yml to update-frontend-webservers.yml would be executed simultaneously and end-deployment-notifications would only start once all the listed items in the previous include had completed.

Rather than overloading 'include' in this way, another keyword might be preferable.  Ideas I have had so far for alternative keyword are 'parallel', 'together', 'fork', or 'join'.

Another implementation might be a separate CLI tool, distinct from ansible-playbook which ran playbooks listed in its own file.  In keeping with the sports name I came up with the name 'league' for the command and 'league-table' as a name for the file format.  On balance I like this idea less as it seems like much more work.  However, you might want to add the ability to specify forks or other playbook command line options (--check perhaps) for each of the parallel playbooks.

Keeping the change within ansible-playbook would make integration with tower and other tools easier.

Here's what a playbook might look like with parallel and some options passed to individual playbooks.

```
    - include: find_release_versions.yml
    - include: synchronize_components_to_datacenter.yml
    - include: pre-deployment-checks.yml
    - include: start-deployment-notifications.yml
    - parallel:
         - { playbook: 'migrate-database.yml', forks: 1, check: True}
         - { playbook: 'migrate-database.yml', forks: 1 }
         - update-compute-nodes.yml
         - update-dequeuers.yml
         - update-web-services.yml
         - update-file-transfer.yml
         - { playbook: 'update-frontend-webservers.yml', forks: 20 }
    - include: end-deployment-notifications.yml
    - include: generate-change-report.yml

```
## Dependencies

I can't think of any dependencies that aren't already in use in ansible-playbook
## Testing

If passing playbook options is included in this functionality, there would be significant testing.  
Possibly useful to enable testing, although this seems to be handled in Shipable at the time of writing.
## Documentation

I can imagine that this feature could possibly cause ansible controllers to run out of resources as it might cause many forks to be generated, so it would need documenting to advise users not to go crazy with it.
