### ISSUE TITLE
ansible-config

### ISSUE THREAD

**Issue by bcoca** [ansible/proposals#35]
# Proposal: ansible-config

*Author*: Brian Coca <@bcoca>

*Date*: 2016/10/-1

- Status: New
- Proposal type: core design
- Targeted Release: future release
- Estimated time to implement: 3 weeks

*Draft implementation*: https://github.com/ansible/ansible/pull/12797

## Motivation
The current configuration system is limited to a single file and previously hardcoded entries in constants.py. We want to allow plays, plugins and even roles to add config settings when they need them.

### Problems
- plugins don't have standardized config entries and adding new/custom plugins requires hardcoding many settings
- Configs are not mergable, sometimes you want to be able to just override a couple of entries and not the whole thing.
- Role that require certain configuration settings are not easily shareable
- There is no current way to 'dump' the config and see the current settings
- Lack of documentation, many config options are left out of the docs and even if added not every way to set an option is detailed.
 
## Solution proposal
- New config.yml that allows for structured config in the familiar YAML format
- New ansible-config command line to allow:
    - dump of current config settings
    - update/write a config entry
    - show available options (ini entry, yaml, env var, etc)
- Definition data for configs also in YAML format, instead of hardcoding into config.py, easy to extend by adding new plugin.yml file as 'config definition'.
- new config setting 'mergable' to allow the current config file to merge with the next priority target one
- new `meta/` dir adjacent to play that can host a config.yml specific

## Other options
  - new `meta/config.yml` for roles, same purpose as play one
  - new setting to toggle reading role's config.yml `read_config_from_role = no|yes`
  - meta/<plugin_type>/<plugin_name>.yml to add config data definition file (config would be in preexisting config.yml)

## Config Data definition 
  - Internal name of setting 
  - ini entry name
  - yaml var name
  - environment var
  - default value
  - inventory var (if applicable)
  - description
  - type

Example config definition file:
```
main:
  ANSIBLE_COW_SELECTION:
      desc: Allows choosing specific cowsay stencils, use 'random' to cycle through them
      ini:
        section: defaults
        key: cow_selection
      env: ANSIBLE_COW_SELECTION
      type: string
      default: null
   DEPRECATION_WARNINGS:
      desc: Controls the display of deprecation warnings.
      ini:
         section: defaults
         key: deprecation_warnings
      yaml:  deprecation_warnings
      env: ANSIBLE_DEPRECATION_WARNINGS
      default:  True
      type: boolean

...

plugins:
  callbacks:
      mail:
        SMTP_HOST:
           desc: Host to use send email via SMTP.
           yaml: smtp_host
           env: SMTPHOST
           default: localhost
```

**Comment by jhawkesworth** [comment]
This would be great, but I'm curious how it would interoperate with vault.
Would it be possible to vault some, but not all of the vars?  It would be good to be able to just vault say passwords for some external service without hiding the hostname.

**Comment by kustodian** [comment]
I really like the idea and the flexibility it gives you, the only thing which I'm not sure I'm the fan of is using YAML, because from your example this ini format:
```
# set which cowsay stencil you'd like to use by default. When set to 'random',
# a random stencil will be selected for each task. The selection will be filtered
# against the `cow_whitelist` option below.
#cow_selection = default
```
is replaced with:
```yaml
  ANSIBLE_COW_SELECTION:
      desc: Allows choosing specific cowsay stencils, use 'random' to cycle through them
      ini:
        section: defaults
        key: cow_selection
      env: ANSIBLE_COW_SELECTION
      type: string
      default: null
```
The ini file is far more easier to read/edit and understand. Of course YAML gives you additional info, but is all of it important except the environment variable which can be used, but you can put the variable in the comment of the ini file as well.

This YAML is awesome when you want to add some new option (as you added `smtp_host`), but for overwriting it isn't the best one, would be cool if for overwriting a value you could just write:

```yaml
main:
  defaults:
    cow_selection: 'defaults'
```
The reason why I'm saying this, is that most often you would like to override some ini value for a project/role/play, but the above option feels too complicated for that.
