### ISSUE TITLE
Allow documenting option deprecation

### ISSUE THREAD

**Issue by bcoca** [ansible/proposals#65]
# Proposal: deprecated doc key for options

*Author*: Brian Coca <@bcoca> IRC: bcoca

*Date*: 2017/06/-1

- Status: New
- Proposal type: doc fields
- Targeted Release: 2.4
- Estimated time to implement: 5mins

## Motivation
There is no way to document the deprecation of an option in plugins.

### Problems
Will allow authors to document deprecation of options.

## Solution proposal
A `deprecated` key that is composed of the following:
```yaml
deprecated:
     why: reason for deprecation
     version: version in which this option is removed
     alternatives: description of alternatives to use
```
## Dependencies (optional)
Doc validator needs to permit
