### ISSUE TITLE
New module/plugin documentation fields

### ISSUE THREAD

**Issue by bcoca** [ansible/proposals#68]
# Proposal: Properties

*Author*: Brian Coca <@bcoca> IRC: bcoca

*Date*: 2017/88/99

- Status: New
- Proposal type: docs
- Targeted Release: Future release
- Estimated time to implement: hours

## Motivation
Clarify and centralize documentation for special behaviours of modules and plugins.

### Problems
- Many of the modules and plugins don't document certain common special behaviors (i.e bypassing host loop) 
- Those that do use different language and position it in notes or descriptions mostly in random fashion.
- This is a LOT of repeat text

## Solution proposal
New 'properties' field in documentation that is a list of 'special properties and/or behaviors' that this module/plugin exhibit.

in plugin docs:
```yaml
features:
  - name: bypass_host_loop
  - name: no_connection
  - name: check_mode
  - name: diff_mode
    version_added: "2.4"
limitations:
 - name: remote_connections
 - name: async
 ```
These then can be mapped to a SINGLE description of what the property means for this plugin, both for ansible-doc and docs website.

Also need to categorize by things that are expected to be supported by default (would have to declare limitation) vs those that are optional (declared in feature).

descriptions.yml:
``` yaml

async: running in asynchronous mode (via async keyword).

bypass_host_loop: behaves as if it had `run_once: true`, which means it won't loop per host but only execute once, any variables will be from the 'first active host' to get to this point. But results are applied to all.

check_mode: running in check mode and reporting on expected change state but not changing things.

diff_mode: reporting expected/transpired changes with before/after differences when diff mode is active.

facts: this action returns ansible_facts

remote_connection: do not connect to the target and solely executes on the controller. # debug is good example

delegation: applies to delegate_to and/or delegate_facts

```

One variation we can have is define all keywords and allow for a `no_` prefix to be a modifier and a single field, instead of 2.
