### ISSUE TITLE
Allow to force data types in YAML after jinja expansion

### ISSUE THREAD

**Issue by Yajo** [ansible/proposals#72]
# Proposal: Allow to force data types in YAML after jinja expansion

*Author*: Jairo Llopis <@Yajo>

*Date*: 2017-09-19

- Status: New
- Proposal type: (core design, process, ?)
- Targeted Release: <future release #, ex. 2.2>
- Associated PR: <link to GH PR in ansible/proposals if PR was submitted>
- Estimated time to implement: <X days, weeks, etc.>

## Motivation
Sometimes you cannot use all of ansible+jinja power if the module did not define the right data type.

### Problems
What problems exist that this proposal will solve?
- https://github.com/ansible/ansible/issues/17992 and all its related issues.

## Solution proposal
As explained in https://github.com/ansible/ansible/issues/15249#issuecomment-330481415, Ansible should allow and parse [YAML application-specific local tags](http://www.yaml.org/spec/1.2/spec.html#tag/local/) that force a type cast *after* the value has been jinja2-evaluated

[YAML itself has already type casters such as `!!int` or `!!float` (double `!!`), but those happen before jinja2, and thus they produce an error](https://github.com/ansible/ansible/issues/15249#issuecomment-287962228).

Basically one should be able to add `!str`, `!int` or `!float` (notice the single `!`) to any variable, either with or without jinja2 expansion, and it should get correctly type-casted after processing the jinja2 filters.

For instance, this should then be a valid workaround for https://github.com/ansible/ansible/issues/30548:

```yaml
- docker_service:
    pull: true
    state: present
    project_name: test
    definition:
      version: "2.2"
      services:
        dind:
          image: docker:dind
          cpus: !float "{{ ansible_processor_cores / 2 }}"
```

## Testing (optional)
A simple `debug` task would be enough to test it IMHO.

## Documentation (optional)
Of course, this should be documented.
