### ISSUE TITLE
new common return `created`

### ISSUE THREAD

**Issue by resmo** [ansible/proposals#78]
# Proposal: new common return `created`

*Author*: René Moser <@resmo> IRC: resmo

*Date*: 2017/10/11

- Status: New
- Proposal type: core design
- Targeted Release: future
- Associated PR: n/a
- Estimated time to implement: n/a

## Motivation
Giving a more detailed view how the resource changed, allowing to conditionally act on new created resources.

### Problems
This allows to fine tune actions depending on new created resources. E.g. only execute this installation script if app was newly installed. 

## Solution proposal
the new common return is a bool, always returned: `created: <true/false>`. A new filter should be added similar to `changed/failed/success/skipped`

Below an example if a resource was created:
```
- apt:
    pkg: foo
  register: result

- assert:
    that:
    - result|success
    - result|changed
    - result|created
    - not result|failed
    - not result|skipped

- shell: /bin/bar
  when: result|created
```
Below an example if a resource was only changed (installed new version of a pkg):
```
- apt:
    pkg: foo
    state: latest
  register: result

- assert:
    that:
    - result|success
    - result|changed
    - not result|created
    - not result|failed
    - not result|skipped
```
For some modules, e.g. command, shell, etc. we can not determine if a resource was created, so we return the default `created: false`.

## Dependencies (optional)
Most likely there will be modules, already returning this new reserved keyword `created` for own purposes. Identify these modules and suggest a different name for the return.

## Testing (optional)
Add tests similar to `changed`

## Documentation (optional)
The new common return should be documented here http://docs.ansible.com/ansible/latest/common_return_values.html#common
