### ISSUE TITLE
Proposed: Common Cloud Credential Usage

### ISSUE THREAD

**Issue by ryansb** [ansible/proposals#90]
# Proposal: Common Cloud Credentials

*Author*: @ryansb

*Date*: 2017/12/18

- Status: New
- Proposal type: Modules Enhancement
- Targeted Release: 2.5 or 2.6
- Associated PR: N/A
- Estimated time to implement: 5 days

## Motivation
Current ways of handling cloud credentials for AWS and other providers is inconsistent, and some of the common usages result in accidentally creating resources in the wrong region/account

## Requirements

- Playbook-wide or site-wide configuration
- Vault-able
- Scoped by the cloud provider (duh)
- Backwards compatible

## Configuration

This would (probably) be implemented as a plugin similarly to the hostvars
plugin, that can use things that are vaulted.

## Alternative

Bless a few magic variable names, so we take advantage of the existing
vaulted-vars and such, allowing all plugins of such-and-such cloud to reach
into the vars system and demand those variables be passed if they exist. I
think this would have to be implemented as a plugin that, when a task is
called, checks if the module is registered as one that needs those special
variables.

The blessed variables would have to be specific enough to not break existing
playbooks, so something like:

```
cloud_credentials:
  aws:
    secret_key: ....
    key_id: ....
    region: ....
  gcp:
    pem_file: ....
    service_account: ....
    region: ....
```

Would be specific enough, and extensible to include any new provider.

## Precedence (most to least specific)

1. Module argument
1. Environment variables
1. Cloud creds (new)
1. User-level config files such as `~/.aws/credentials` and `~/.aws/config`
1. System-level config such as `/etc/boto.cfg`
1. External config such as EC2 Instance Roles

### Repeated Variables

The most common way in examples & playbooks I see around is to set variables
`aws_*_key` and `aws_region` and use those throughout:

```
- hosts: localhost
  vars:
    aws_secret_access_key: sekrit
    aws_access_key_id: AKAI....
    aws_region: us-weast-9
  tasks:
  - ec2:
      region: "{{ aws_region }}"
      aws_secret_access_key: "{{ aws_secret_access_key }}"
      aws_access_key_id: "{{ aws_access_key_id }}"
```

I also have seen lots of IRC problems where people forget to copy/paste the
`region` on all tasks, and are then surprised their playbook doesn't work right
outside us-east-1 (the default region).

### Environment Variables

Today, Tower passes AWS credentials in this way. It sets the
`AWS_ACCESS/SECRET_KEY` variables and those env vars are used as normal. Tower
provides a nice UI for this so *most* users of Tower wouldn't need/notice a new
way of providing cloud credentials.

For sections of plays, users can do:

```
- block:
    environment:
      AWS_SECRET_ACCESS_KEY: .....
    tasks:
      - ec2: ....
```

But that means users have to sometimes put full playbooks inside of blocks, and
if they want to have separate error/rescue handling they then have to nest
blocks.

### YAML Anchors

YAML has a feature that lets you create prototypes based on an item, you
declare it with `&your_anchor_name` and then it can be exploded into any
similar type. In some tests we use a YAML anchor to share credentials among all
the AWS tasks instead of repeating var-usage (not-quite-right #1)

```
- set_fact:
    aws_creds: &aws_creds
      aws_secret_access_key: sekrit
      aws_access_key_id: AKAI....
      region: us-weast-9
- ec2:
    <<: *aws_creds
    arg1: val1
    arg2: val2
```

## Other Considerations

Also to consider: MFA/role users. I don't want to reimplement boto profiles
because madness lies down that path, but for other cloud providers we're going
to have similar requirements and their MFA/SDK situation isn't as nice.
